// Seeds the Neo4j skill knowledge graph. Mirrors apps/api/app/data/seed_skills.py
// SKILL_GRAPH_EDGES so the graph provider (real Neo4j or in-memory mock) agrees.
//
// Run: cypher-shell -u neo4j -p intellimatch -f neo4j/seed.cypher

MERGE (java:Skill {name: "Java"})
MERGE (spring:Skill {name: "Spring Boot"})
MERGE (rest:Skill {name: "REST APIs"})
MERGE (micro:Skill {name: "Microservices"})
MERGE (docker:Skill {name: "Docker"})
MERGE (k8s:Skill {name: "Kubernetes"})
MERGE (aws:Skill {name: "AWS"})
MERGE (azure:Skill {name: "Azure"})
MERGE (gcp:Skill {name: "GCP"})
MERGE (python:Skill {name: "Python"})
MERGE (ml:Skill {name: "Machine Learning"})
MERGE (dl:Skill {name: "Deep Learning"})
MERGE (pytorch:Skill {name: "PyTorch"})
MERGE (sklearn:Skill {name: "scikit-learn"})
MERGE (nlp:Skill {name: "NLP"})
MERGE (llm:Skill {name: "LLM Engineering"})
MERGE (js:Skill {name: "JavaScript"})
MERGE (react:Skill {name: "React"})
MERGE (next:Skill {name: "Next.js"})
MERGE (node:Skill {name: "Node.js"})
MERGE (sql:Skill {name: "SQL"})
MERGE (postgres:Skill {name: "PostgreSQL"})
MERGE (git:Skill {name: "Git"})
MERGE (cicd:Skill {name: "CI/CD"})

MERGE (java)-[:LEADS_TO]->(spring)
MERGE (spring)-[:LEADS_TO]->(rest)
MERGE (rest)-[:LEADS_TO]->(micro)
MERGE (micro)-[:LEADS_TO]->(docker)
MERGE (docker)-[:LEADS_TO]->(k8s)
MERGE (k8s)-[:LEADS_TO]->(aws)
MERGE (aws)-[:RELATED_TO]->(azure)
MERGE (aws)-[:RELATED_TO]->(gcp)
MERGE (python)-[:LEADS_TO]->(ml)
MERGE (ml)-[:LEADS_TO]->(dl)
MERGE (dl)-[:LEADS_TO]->(pytorch)
MERGE (ml)-[:RELATED_TO]->(sklearn)
MERGE (nlp)-[:RELATED_TO]->(llm)
MERGE (js)-[:LEADS_TO]->(react)
MERGE (react)-[:LEADS_TO]->(next)
MERGE (node)-[:RELATED_TO]->(rest)
MERGE (sql)-[:RELATED_TO]->(postgres)
MERGE (docker)-[:PREREQUISITE_OF]->(k8s)
MERGE (git)-[:PREREQUISITE_OF]->(cicd);
