"use client";

import { useState } from "react";
import { AlertCircle, CheckCircle, HelpCircle, RefreshCw, XCircle } from "lucide-react";
import { api } from "@/lib/api";
import type { AssessmentQuestionItem, AssessmentResultItem } from "@/types/api";
import { Card, LoadingBlock, PageHeader, Pill } from "@/components/ui";

const TARGET_SKILLS = ["AWS", "Docker", "Kubernetes", "System Design", "Microservices", "Python", "SQL"];

export default function AssessmentPage() {
  const [selectedSkill, setSelectedSkill] = useState<string>("AWS");
  const [questions, setQuestions] = useState<AssessmentQuestionItem[] | null>(null);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AssessmentResultItem | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    setResult(null);
    setSelectedAnswers({});
    try {
      const res = await api.assessmentGenerate("Senior Backend Engineer", ["AWS", "Kubernetes", "System Design"], selectedSkill);
      setQuestions(res.questions);
    } catch (err: any) {
      setError(err?.message || "AI assessment generation is temporarily unavailable. Please verify your OpenRouter API key.");
    } finally {
      setLoading(false);
    }
  }

  async function submit() {
    if (!questions || questions.length === 0) return;
    setLoading(true);
    setError(null);
    try {
      const payload = questions.map((q, i) => ({
        question: q.prompt,
        user_answer: selectedAnswers[i] !== undefined ? selectedAnswers[i] : -1,
        correct_answer: q.correct_answer !== undefined ? q.correct_answer : 0,
        explanation: q.explanation || "",
      }));
      const res = await api.assessmentEvaluate(payload);
      setResult(res);
    } catch (err: any) {
      setError(err?.message || "Unable to grade assessment. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  function handleSelectOption(qIndex: number, optIndex: number) {
    if (result) return; // Locked once evaluated
    setSelectedAnswers((prev) => ({ ...prev, [qIndex]: optIndex }));
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Technical Assessment"
        subtitle="Role-targeted multiple-choice and scenario questions generated by OpenRouter AI from your skill gaps."
      />

      <Card>
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-2">
              Select Competency Assessment Focus
            </p>
            <div className="flex flex-wrap gap-2">
              {TARGET_SKILLS.map((s) => (
                <button
                  key={s}
                  onClick={() => setSelectedSkill(s)}
                  className={`rounded-full border px-3 py-1 text-xs font-semibold transition-all ${
                    selectedSkill === s
                      ? "border-brand-600 bg-brand-600 text-white shadow-sm"
                      : "border-slate-200 bg-white text-slate-600 hover:border-slate-300"
                  }`}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>
          <button
            onClick={generate}
            disabled={loading}
            className="btn-primary shrink-0"
          >
            {loading ? "Generating Assessment..." : `Start ${selectedSkill} Assessment`}
          </button>
        </div>
      </Card>

      {error && (
        <Card className="border-red-200 bg-red-50/50 p-4">
          <div className="flex items-start gap-3">
            <AlertCircle className="h-5 w-5 text-red-600 shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-semibold text-red-900">Assessment generation error</p>
              <p className="text-xs text-red-700 mt-0.5">{error}</p>
            </div>
          </div>
        </Card>
      )}

      {loading && <LoadingBlock label="Generating verified questions with OpenRouter AI..." />}

      {/* Results Overview Card */}
      {result && (
        <Card className="border-brand-200 bg-gradient-to-br from-brand-50/40 to-indigo-50/30 p-5">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p className="text-xs font-bold uppercase tracking-wider text-brand-700">Assessment Completed</p>
              <div className="mt-1 flex items-baseline gap-2">
                <span className="text-3xl font-extrabold text-slate-900">{result.score}%</span>
                <span className="text-sm text-slate-600">
                  ({result.correct_count} of {result.total_questions} questions correct)
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-1">
                Score calculated deterministically by IntelliMatch validation engine.
              </p>
            </div>
            <button
              onClick={generate}
              className="inline-flex items-center gap-1.5 rounded-lg border border-brand-300 bg-white px-3.5 py-2 text-xs font-bold text-brand-700 hover:bg-brand-50"
            >
              <RefreshCw size={13} /> Retake Assessment
            </button>
          </div>
        </Card>
      )}

      {/* Question List */}
      {questions && !loading && (
        <div className="space-y-4">
          {questions.map((q, qIndex) => {
            const isAnswered = selectedAnswers[qIndex] !== undefined;
            const evalItem = result?.breakdown?.[qIndex];
            const isCorrect = evalItem?.is_correct;

            return (
              <Card key={qIndex} className="space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="flex h-5 w-5 items-center justify-center rounded-full bg-slate-100 text-[10px] font-bold text-slate-600">
                      {qIndex + 1}
                    </span>
                    <Pill tone="brand">{q.type || "Technical Concept"}</Pill>
                  </div>
                  {result && (
                    isCorrect ? (
                      <span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-600">
                        <CheckCircle size={14} /> Correct
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1 text-xs font-bold text-rose-600">
                        <XCircle size={14} /> Incorrect
                      </span>
                    )
                  )}
                </div>

                <p className="text-sm font-semibold text-slate-900">{q.prompt}</p>

                {/* Options List */}
                {q.options && q.options.length > 0 && (
                  <div className="grid gap-2 sm:grid-cols-2 pt-1">
                    {q.options.map((opt, optIndex) => {
                      const isSelected = selectedAnswers[qIndex] === optIndex;
                      const isCorrectChoice = result && q.correct_answer === optIndex;
                      const isWrongSelection = result && isSelected && !isCorrectChoice;

                      let btnStyle = "border-slate-200 bg-white text-slate-700 hover:border-slate-300";
                      if (result) {
                        if (isCorrectChoice) {
                          btnStyle = "border-emerald-500 bg-emerald-50 text-emerald-900 font-semibold";
                        } else if (isWrongSelection) {
                          btnStyle = "border-rose-300 bg-rose-50 text-rose-900";
                        } else {
                          btnStyle = "border-slate-100 bg-slate-50 text-slate-400 opacity-60";
                        }
                      } else if (isSelected) {
                        btnStyle = "border-brand-600 bg-brand-50 text-brand-900 font-semibold shadow-xs ring-1 ring-brand-600";
                      }

                      return (
                        <button
                          key={optIndex}
                          type="button"
                          onClick={() => handleSelectOption(qIndex, optIndex)}
                          disabled={!!result}
                          className={`flex items-start gap-2.5 rounded-lg border p-3 text-left text-xs transition-all ${btnStyle}`}
                        >
                          <span className="font-bold shrink-0">
                            {String.fromCharCode(65 + optIndex)}.
                          </span>
                          <span className="flex-1">{opt}</span>
                        </button>
                      );
                    })}
                  </div>
                )}

                {/* Explanation on result */}
                {result && evalItem?.explanation && (
                  <div className="mt-2 rounded-md bg-slate-50 border border-slate-100 p-2.5 text-xs text-slate-600">
                    <span className="font-bold text-slate-800">Explanation: </span>
                    {evalItem.explanation}
                  </div>
                )}
              </Card>
            );
          })}

          {!result && (
            <div className="flex justify-end pt-2">
              <button
                onClick={submit}
                disabled={loading || Object.keys(selectedAnswers).length < (questions.length || 1)}
                className="btn-primary"
              >
                {loading ? "Grading..." : `Submit Assessment (${Object.keys(selectedAnswers).length}/${questions.length} answered)`}
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

